# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tsimg_gif_rcpp <- function(image_paths, frame_delay = 100L, debug = FALSE, reverse = FALSE) {
    .Call(`_tsimgR_tsimg_gif_rcpp`, image_paths, frame_delay, debug, reverse)
}

